---
- name: create iptables rules directory
  file: path=/etc/iptables owner=root group=root state=directory
  tags:
    - iptables

- name: copy iptables rules
  # we want to copy new rules only once: at the host init, hence force=no
  template: src=../templates/rules.v4.proxy dest=/etc/iptables/rules.v4.init owner=root group=root mode=0644 force=no
  tags:
    - iptables
  notify:
    - restore iptables
    - save iptables

- name: install iptables persitence scripts
  # we do it after copying the rules, as otherwise we will get empty rules file
  action: apt pkg=$item
  with_items:
      - iptables-persistent
  tags:
    - iptables
