---
- name: ensure apt repo is up to date
  action: apt update-cache=yes
  tags:
    - prereq

- name: ensure dependency packages are installed
  action: apt pkg=$item
  with_items:
      - xfsprogs
      - python-parted
  tags:
    - prereq

- name: create iptables rules directory
  file: path=/etc/iptables owner=root group=root state=directory
  tags:
    - iptables

- name: copy iptables rules
  # we want to copy new rules only once: at the host init, hence force=no
  template: src=../templates/rules.v4.storage dest=/etc/iptables/rules.v4.init owner=root group=root mode=0644 force=no
  tags:
    - iptables
  notify:
    - restore iptables
    - save iptables

- name: install iptables persitence scripts
  action: apt pkg=$item
  with_items:
      - iptables-persistent
  tags:
    - iptables
