---

- name: Recheck partitions
  parted: minsize={{ min_storage_partition }} repeated=yes filesystem=xfs
  when: disk_strategy == 'rackspace'
  tags:
    - rings

- name: Set permissions for storage devices
  file: path=/srv/node/{{ item.name }} owner=swift group=swift state=directory
  when: disk_strategy == 'rackspace'
  with_items: parted_existing
  tags:
    - rings

- name: Create rings
  shell: creates=/etc/swift/{{ item }}.builder swift-ring-builder /etc/swift/{{ item }}.builder create 8 3 1
  delegate_to: "{{ groups['zwift.proxy'][0] }}"
  with_items:
    - object
    - container
    - account
  tags:
    - rings

- name: Update rings
  command: swift-ring-builder /etc/swift/{{ item[1].file }} add r{{ rax_metadata.region}}z{{ rax_metadata.zone }}-{{ hostvars[inventory_hostname]["ansible_" ~ storage_internal_interface]["ipv4"]["address"] }}:{{ item[1].port }}/{{ item[0].name }} {{ item[0].size // 1000000 * device_weight }}
  register: ring_builder_result
  ignore_errors: True
  when: disk_strategy == 'rackspace'
  with_nested:
    - parted_existing
    - [ { 'file': 'object.builder', 'port': '6000' }, { 'file': 'container.builder', 'port': '6001' }, { 'file': 'account.builder', 'port': 6002 } ]
  delegate_to: "{{ groups['zwift.proxy'][0] }}"
  tags:
    - rings

