---
- name: restore iptables
  action: shell iptables-restore < /etc/iptables/rules.v4.init

- name: save iptables
  action: shell iptables-save > /etc/iptables/rules.v4

- name: update chef clients
  shell: chef-client

- name: restart apache
  action: service name=apache2 state=restarted

