---
- hosts: zwift.chef-server
  user: root
  gather_facts: true
  vars_files:
    - "../rackspace_vars.yaml"

  tasks:

  - name: install chef server
    shell: creates=/etc/chef-server/chef-server.rb executable=/bin/bash curl -s -L https://raw.github.com/rcbops/support-tools/master/chef-install/install-chef-server.sh | bash

  - name: update bookshelf
    lineinfile: dest=/etc/chef-server/chef-server.rb insertbefore=BOF regexp='bookshelf\["vip"\]' line='bookshelf["vip"] = "{{ hostvars[groups['zwift.chef-server'][0]]['ansible_' ~ chef_server_interface]['ipv4']['address'] }}"'
    notify:
      - reconfigure chef-server
    tags:
      - fixdns
    
  - name: install packages
    apt: pkg={{ item }}
    with_items:
      - git
      - ruby1.9.3
      - libxml2-dev
      - libxslt1-dev
      - build-essential
      - zlib1g-dev
      - make

  - name: install berkshelf
    gem: name=berkshelf state=latest

  - name: get rcbops cookbooks from git
    git: repo={{ cookbook.repo }} dest={{ cookbook.dir }} version={{ cookbook.version }}
    notify:
      - upload cookbooks
      - upload cookbook roles

  - name: get swift-lite dependencies from git
    git: repo={{ opscode}}/{{ item }} dest={{ cookbook.dir }}/cookbooks/{{ item }}
    with_items:
      - chef_handler
      - windows
      - dmg
      - git
      - cron
    notify:
      - upload cookbooks

  - name: get swift-lite cookbook from git
    git: repo={{ swift_lite.repo }} dest={{ cookbook.dir }}/cookbooks/swift-lite version={{ swift_lite.version }}
    notify:
      - upload cookbooks
      - upload swift-lite roles

#  - name: get swift-private-cloud cookbook from git
#    git: repo={{ swift_private_cloud.repo }} dest={{ cookbook.dir }}/swift-private-cloud version={{ swift_private_cloud.version }}
#    notify:
#      - upload to berkshelf
#      - upload swift-private-cloud roles

  handlers:
  
  - name: upload cookbooks
    shell: chdir={{ cookbook.dir }} executable=/bin/bash /opt/chef-server/bin/knife cookbook upload -a -o cookbooks

#  - name: upload to berkshelf
#    shell: chdir={{ cookbook.dir }}/swift-private-cloud berks install; berks upload

  - name: upload cookbook roles
    shell: chdir={{ cookbook.dir }} executable=/bin/bash /opt/chef-server/bin/knife role from file roles/*.rb

  - name: upload swift-lite roles
    shell: chdir={{ cookbook.dir }}/cookbooks/swift-lite/contrib executable=/bin/bash /opt/chef-server/bin/knife role from file roles/*.rb

#  - name: upload swift-private-cloud roles
#    shell: chdir={{ cookbook.dir }}/swift-private-cloud executable=/bin/bash /opt/chef-server/bin/knife role from file roles/*.rb

  - name: reconfigure chef-server
    command: chef-server-ctl reconfigure

